name: Dev Environment Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy with Security Scanning
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Secret Scanning with GitLeaks
      - name: Secret Scan with GitLeaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config: false
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Dependency Scanning with OWASP Dependency-Check
      - name: Dependency Scan with OWASP Dependency-Check
        uses: dependency-check/action@v1.4.0
        with:
          project: "My Project"
          format: "ALL"
          scan_path: "${{ github.workspace }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Vulnerability Scan with Trivy for container images
      - name: Container Image Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ubuntu-latest"
          format: "table"
          ignore-unfixed: true

      # Build and Deploy Job
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "."

      # Create Pull Request to QA
      - name: Create Pull Request to QA
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dev into qa"
          title: "Pull Request: Merge dev into qa"
          body: "This PR merges the changes from dev into qa."
          base: qa
          head: dev
          branch: dev-to-qa-automated-pr
